[STAYAWAY-8] integration tests infra, tests for game service and draw
tilacyn/stay-away pull request #14
Opened 2022-08-27 09:13 UTC by tilacyn

2022-08-27 09:33 UTC, tilacyn commented
Можно было бы еще тестов написать на draw,  например, какую конкретно карту вытаскиваешь, но тогда надо мокать CardDistributor. Можно и нужно будет это сделать впоследствии

2022-08-27 09:33 UTC, tilacyn commented on pom.xml
> +            <groupId>org.testcontainers</groupId>
Будем использовать не embedded mongo, а testcontainers на основе докера.
Для того чтобы тесты работали надо подтянуть пару образов
`docker pull mongo:4.4.2`
`docker pull testcontainers/ryuk:0.3.0`

2022-08-27 09:33 UTC, tilacyn commented on src/main/java/com/stayaway/dao/model/builder/BoardUpdateBuilder.java
> +        return Board.builder()
Пока так (toBuilder плохо потому что она handler'ы копирует и что-то в сериализации ломается). В дальнейшем планируем сделать кастомный билдер

2022-08-27 09:33 UTC, tilacyn commented on src/main/java/com/stayaway/exception/StayAwayException.java
> +    public String getMessage() {
Иначе логгировал StayAwayException: null (дальше стектрейс)

2022-08-27 09:33 UTC, tilacyn commented on src/main/java/com/stayaway/response/BoardResponse.java
> -    private final List<PlayerResponse> players;
Jackson хочет NoArgsConstructor

2022-08-27 09:33 UTC, tilacyn commented on src/test/java/com/stayaway/TestBoardFactory.java
> +    protected Set<String> getGameUserLogins(Game game) {
Вот эти два метода - дырки в которых мы мокаем пользователей и из порядок

2022-08-27 16:09 UTC, Kowalski1337 commented on pom.xml
> +            <groupId>org.testcontainers</groupId>
А это не может быть в одном контейнере?

2022-08-27 16:34 UTC, Kowalski1337 requested changes

2022-08-27 16:34 UTC, Kowalski1337 commented on src/test/java/com/stayaway/TestMvc.java
> +class TestMvc {
Я правильно понимаю, что это штука для заполнения данными, на которых нужно протестить?

Если так, то имхо тесты должны заполнять данные чуть ли не в базу, чтоб быть независимыми от другой функциональности. у тебя сейчас если кто-то сломает создание игры как будто бы упадут все тесты

2022-08-27 16:34 UTC, Kowalski1337 commented on src/test/java/com/stayaway/GameServiceTest.java
> +    private MockMvc mvc;
А в тестах нельзя как-то избежать autowired?

А то чет везде рекомендуют инжектить в конструктор
https://stackoverflow.com/questions/40620000/spring-autowire-on-properties-vs-constructor

2022-08-27 16:34 UTC, Kowalski1337 commented on src/test/java/com/stayaway/GameServiceTest.java
> +        var testMvc = new TestMvc(mvc);
А это точно надо в каждом тесте создавать, а не на пачку тестов?

2022-08-27 16:34 UTC, Kowalski1337 commented on src/test/java/com/stayaway/GameServiceTest.java
> +import static org.assertj.core.api.Assertions.assertThat;
Обычно юзал org.junit.Assert и org.hamcrest.Matchers

Возмоно вкусовщина, но надо почитать

2022-08-27 16:34 UTC, Kowalski1337 commented on src/test/java/com/stayaway/GameServiceTest.java
> +import org.junit.Before;
Так-то у тебя какая-то помесь тестовых либ, вот тут ты таки org.junit используешь

2022-08-27 16:34 UTC, Kowalski1337 commented on src/test/java/com/stayaway/GameServiceTest.java
> +    static MongoDBContainer mongoDBContainer = new MongoDBContainer("mongo:4.4.2");
Надо бы чтоб ты голосом объяснил как это работает

Но можешь приложить в задачу ресурсы откуда ты читал про это

2022-08-27 16:34 UTC, Kowalski1337 commented on src/test/java/com/stayaway/GameServiceTest.java
> +    public void should_createAndGetCurrentBoard() {
мне не нравится такое название тестов

Больше нравится testCreateAndGetCurrentBoard
А еще тут ты тестируешь сразу два сценария
Такое имхо должно быть так: тестируешь создание -> проверяешь, что в базе лежит
Кладешь в базу -> проверяешь что корректно отдается в ручке получения

После наличия таких двух базовых сценариях в остальных сценариях уже можно пользоваться фактом того, что это он работает и не писать в базу/проверять что записалось в базу. А работать через менеджеры.

2022-08-27 16:34 UTC, Kowalski1337 commented on src/test/java/com/stayaway/GameServiceTest.java
> +public class GameServiceTest {
А еще я бы разнес тетирование разных слоев в разные тесты.

Ex:
CreateGameServiceTest
CreateGameControllerTest/CreateGameTest

2022-08-27 16:34 UTC, Kowalski1337 commented on src/test/java/com/stayaway/GameServiceTest.java
> +        assertThat(boardResponse.getCards()).size().isEqualTo(4);
Стоит ли завести глобальную константу на число карт?

2022-08-27 16:34 UTC, Kowalski1337 commented on src/test/java/com/stayaway/TestBoardFactory.java
> +public class TestBoardFactory extends BasicBoardFactory {
А эта компонента не будет включена в общую сборку?

2022-08-27 16:34 UTC, Kowalski1337 commented on src/test/java/com/stayaway/TestBoardFactory.java
> +public class TestBoardFactory extends BasicBoardFactory {
Как будто бы разнести это на разные конфиги - норм тема

2022-08-27 16:34 UTC, Kowalski1337 commented on src/test/java/com/stayaway/TestBoardFactory.java
> +public class TestBoardFactory extends BasicBoardFactory {
Нужно погуглить как заводить правильно тестовый инжектор. Или спринг умный и так за нас это сделал потому что эта компонента в папочке test?

2022-08-27 16:34 UTC, Kowalski1337 commented on src/test/java/com/stayaway/DrawGameplayTest.java
> +        var testMvc = new TestMvc(mvc);
Вообще хочется такие вещи как раз унести куда-то под капот. Например завести какой-то класик, у которого будет внутри GameService и мы в тестах его чем-то кормим а потом вызываем создай. Можно тут прикрутить прикольный паттерн для тестов. Т.н. степы. Расскажу голосом.

2022-08-27 16:44 UTC, tilacyn commented on src/test/java/com/stayaway/TestBoardFactory.java
> +public class TestBoardFactory extends BasicBoardFactory {
Да, он не включит это в production контекст, потому что это в папке test

2022-08-27 16:57 UTC, tilacyn commented on src/test/java/com/stayaway/GameServiceTest.java
> +        var testMvc = new TestMvc(mvc);
На каждый класс, но не на каждый тест, сделаю полем

2022-08-27 16:57 UTC, tilacyn commented on src/test/java/com/stayaway/GameServiceTest.java
> +    private MockMvc mvc;
Да можно наверное

2022-08-27 16:58 UTC, tilacyn commented on src/test/java/com/stayaway/TestMvc.java
> +class TestMvc {
Ну мне влом было заполнять данные в базу руками, решил пока так

2022-08-27 17:00 UTC, tilacyn commented on src/test/java/com/stayaway/GameServiceTest.java
> +import org.junit.Before;
Ну в junit есть Before, но нету assertThat, assertThat помощнее поэтому решил его использовать для обычных ассертов, можно потом переделать, как удобнее будет

2022-08-27 17:02 UTC, tilacyn commented on src/test/java/com/stayaway/GameServiceTest.java
> +    public void should_createAndGetCurrentBoard() {
Я просто дергаю ручки в таком же порядке, как они будут дергаться в продакшне. Такой сценарий интеграционных тестов в любом случае полезен, и так проще всего. В дальнейшем можно будет сделать запись/чтение напрямую из базы.

2022-08-27 17:02 UTC, tilacyn commented on src/test/java/com/stayaway/GameServiceTest.java
> +public class GameServiceTest {
Ну мы вообще не представляем пока в какой степени и какие слои будем тестировать, предлагаю потом

2022-08-27 17:04 UTC, tilacyn commented on src/test/java/com/stayaway/GameServiceTest.java
> +        assertThat(boardResponse.getCards()).size().isEqualTo(4);
Ну можно, но надо думать как ее назвать куда положить, и карт бывает 4 в руке, а бывает 5, короче хз пока.

2022-08-27 17:05 UTC, tilacyn commented on src/test/java/com/stayaway/DrawGameplayTest.java
> +        var testMvc = new TestMvc(mvc);
Так я же и унес под капот в TestMvc.createAndStart, это абстракция на уровне rest api

2022-08-27 17:05 UTC, tilacyn commented on src/test/java/com/stayaway/DrawGameplayTest.java
> +        var testMvc = new TestMvc(mvc);
Паттерны можно, но не в этом пр, наверное

2022-08-27 18:45 UTC, tilacyn commented on src/test/java/com/stayaway/GameServiceTest.java
> +    static MongoDBContainer mongoDBContainer = new MongoDBContainer("mongo:4.4.2");
Вот туториал
https://rieckpil.de/mongodb-testcontainers-setup-for-datamongotest/

В методе ниже проставляется пропертя spring.data.mongodb.uri, больше это не используется. testContainers поднимает монгу в докер контейнере, мы просто обращаемся к ней через обычные компоненты: репозитории/MongoTemplate etc

2022-08-27 19:09 UTC, tilacyn commented on src/test/java/com/stayaway/GameServiceTest.java
> +    private MockMvc mvc;
Autowired синонимичен Inject. Inject почему-то не работает, сделал Autowired на конструкторе

2022-08-27 19:09 UTC, tilacyn commented on src/test/java/com/stayaway/GameServiceTest.java
> +        var testMvc = new TestMvc(mvc);
Сделал

2022-08-28 06:56 UTC, myutman requested changes

2022-08-28 06:56 UTC, myutman commented on src/test/java/com/stayaway/DrawGameplayTest.java
> +    static MongoDBContainer mongoDBContainer = new MongoDBContainer("mongo:4.4.2");
Константа в коде. Может быть вынесем куда-нибудь в properties? (а то вдруг версия обновится, надо будет тестировать с обновленной)

2022-08-28 06:56 UTC, myutman commented on src/test/java/com/stayaway/DrawGameplayTest.java
> +        registry.add("spring.data.mongodb.uri", mongoDBContainer::getReplicaSetUrl);
Вот тут меня константа тоже смущает, но тут можно в какое-нибудь static-поле вынести

2022-08-28 06:56 UTC, myutman commented on src/test/java/com/stayaway/GameServiceTest.java
> +    static MongoDBContainer mongoDBContainer = new MongoDBContainer("mongo:4.4.2");
аналогично src/test/java/com/stayaway/DrawGameplayTest.java

2022-08-28 06:56 UTC, myutman commented on src/test/java/com/stayaway/GameServiceTest.java
> +        registry.add("spring.data.mongodb.uri", mongoDBContainer::getReplicaSetUrl);
аналогично src/test/java/com/stayaway/DrawGameplayTest.java

2022-08-28 06:56 UTC, myutman commented on src/test/java/com/stayaway/DrawGameplayTest.java
> +    }
Раз это интеграционные тесты, хорошо было бы проверить еще и корректность состояния в базе

2022-08-28 06:56 UTC, myutman commented on src/test/java/com/stayaway/DrawGameplayTest.java
> +        testMvc.expectDrawNotAllowed(gameId, player2);
тут два раза у player2 проверка, так и надо?

2022-08-28 10:03 UTC, tilacyn commented on src/test/java/com/stayaway/DrawGameplayTest.java
> +        testMvc.expectDrawNotAllowed(gameId, player2);
Ну да, почему нет

2022-08-28 10:04 UTC, tilacyn commented on src/test/java/com/stayaway/DrawGameplayTest.java
> +    }
В этом пр написаны простые тесты на rest api без хождения руками в базу. Можно сделать это, но предлагаю в другом пр

2022-08-28 10:12 UTC, tilacyn commented on src/test/java/com/stayaway/GameServiceTest.java
> +        registry.add("spring.data.mongodb.uri", mongoDBContainer::getReplicaSetUrl);
Сделал

2022-08-28 10:12 UTC, tilacyn commented on src/test/java/com/stayaway/GameServiceTest.java
> +    static MongoDBContainer mongoDBContainer = new MongoDBContainer("mongo:4.4.2");
Сделал

2022-08-28 10:12 UTC, tilacyn commented on src/test/java/com/stayaway/DrawGameplayTest.java
> +        registry.add("spring.data.mongodb.uri", mongoDBContainer::getReplicaSetUrl);
Сделал

2022-08-28 10:12 UTC, tilacyn commented on src/test/java/com/stayaway/DrawGameplayTest.java
> +    static MongoDBContainer mongoDBContainer = new MongoDBContainer("mongo:4.4.2");
Сделал

2022-08-28 11:07 UTC, Kowalski1337 commented on src/test/java/com/stayaway/GameServiceTest.java
> +import org.junit.Before;
Есть

2022-08-28 11:08 UTC, Kowalski1337 commented on src/test/java/com/stayaway/GameServiceTest.java
> +public class GameServiceTest {
Я слабо верю в то, что тесты переписываются когда-то 

Так что не понимаю почему не нужно сейчас таким заниматься

2022-08-28 11:09 UTC, Kowalski1337 commented on src/test/java/com/stayaway/GameServiceTest.java
> +        assertThat(boardResponse.getCards()).size().isEqualTo(4);
Ну ладно, это актуально только если стартовое число карт захотим делать отличное от 4))))

2022-08-28 11:20 UTC, Kowalski1337 requested changes

2022-08-28 11:20 UTC, Kowalski1337 commented on src/test/java/com/stayaway/TestMvc.java
> +    void expectDrawNotAllowed(String gameId, String login) throws Exception {
Имхо такая проверка должна быть непосредственно в тесте

В базовом классе должен быть draw(), который возвращает Response, у которого ты проверяешь статус и контент в тесте

2022-08-28 11:20 UTC, Kowalski1337 commented on src/test/java/com/stayaway/TestMvc.java
> +    void expectDrawNotAllowed(String gameId, String login) throws Exception {
Иначе этот базовый класс превратится в помойку через 2-3 итерации написания тестов

2022-08-28 12:02 UTC, tilacyn commented on src/test/java/com/stayaway/GameServiceTest.java
> +public class GameServiceTest {
У меня нет чёткого понимания, что делать два класса лучше и понятнее чем один. Потому что я не представляю какие тесты будут впоследствии. Если есть желание сделать два класса - пожалуйста, можешь сделать

2022-08-28 12:11 UTC, tilacyn commented on src/test/java/com/stayaway/TestMvc.java
> +    void expectDrawNotAllowed(String gameId, String login) throws Exception {
Там проверки в монаде происходят. возвращать монады из testmvc тоже не очень круто.
Помойку я не планировал, потому что в моём понимании пока есть два основных кейса - метод разрешён и метод не разрешён.

2022-08-28 12:16 UTC, tilacyn commented on src/test/java/com/stayaway/GameServiceTest.java
> +public class GameServiceTest {
Точнее как-то представляю и в моем представлении это скорее не нужно

2022-08-28 12:39 UTC, tilacyn commented on src/test/java/com/stayaway/GameServiceTest.java
> +import org.junit.Before;
Ок, посмотрю

2022-08-28 14:29 UTC, merged