[STAYAWAY-23] play which does the same as discard
tilacyn/stay-away pull request #19
Opened 2022-09-03 20:15 UTC by tilacyn

2022-09-03 20:19 UTC, tilacyn commented on src/test/java/com/stayaway/PlayGameplayTest.java
> +        testMvc.expectPlayStatus(gameId, player1, wrongTargetRequest, 400);
типо таргета нет за столом - это 400, а на таргета нельзя сыграть - это 409 (сейчас второй вариант не делаем)

2022-09-03 20:19 UTC, tilacyn commented on src/test/java/com/stayaway/PlayGameplayTest.java
> +public class PlayGameplayTest {
тут почти то же что и в дискард тестах но еще проверки на таргет

2022-09-03 20:19 UTC, tilacyn commented on src/main/java/com/stayaway/core/state/ChoosingCardBoardState.java
> +            throw StayAwayException.badRequest(String.format("target player [%s] not found", target));
Некруто ловить StayAwayException, но что поделать, пока оставляем так.
В другом комменте отписался почему это bad request

2022-09-03 23:01 UTC, Kowalski1337 requested changes

2022-09-03 23:01 UTC, Kowalski1337 commented on src/main/java/com/stayaway/request/PlayRequest.java
> +    private CardType cardType;
Должен принимать номер карты, можешь заодно в дискарде поправить? 
https://tracker.yandex.ru/STAYAWAY-32

2022-09-03 23:01 UTC, Kowalski1337 commented on src/test/java/com/stayaway/PlayGameplayTest.java
> +        testMvc.expectPlayStatus(gameId, player1, wrongTargetRequest, 400);
401

2022-09-03 23:04 UTC, Kowalski1337 commented on src/test/java/com/stayaway/PlayGameplayTest.java
> +        testMvc.expectPlayStatus(gameId, player1, wrongTargetRequest, 400);
403 а не 400, имхо

А 400 это то, что мы должны отвечать вместо 500, когда неверный формат данных пришел

2022-09-03 23:05 UTC, Kowalski1337 commented on src/main/java/com/stayaway/core/state/ChoosingCardBoardState.java
> +            throw StayAwayException.badRequest(String.format("target player [%s] not found", target));
bad request это про то, что у тебя в нужную ручку в нужном контексте неверные данные пришли

2022-09-03 23:12 UTC, Kowalski1337 commented on src/test/java/com/stayaway/PlayGameplayTest.java
> +        testMvc.expectPlayStatus(gameId, player1, wrongTargetRequest, 400);
Не, 400 должно быть, все ок

2022-09-03 23:24 UTC, Kowalski1337 requested changes

2022-09-03 23:24 UTC, Kowalski1337 commented on src/main/java/com/stayaway/request/PlayRequest.java
> +@AllArgsConstructor
Только сейчас обратил внимание, мне кажется тут еще не хватает
@Setter
@Getter

))

(зачем что-то кроме DATA???)

2022-09-03 23:25 UTC, Kowalski1337 commented on src/main/java/com/stayaway/request/PlayRequest.java
> +    private CardType cardType;
final

2022-09-03 23:36 UTC, tilacyn commented on src/main/java/com/stayaway/request/PlayRequest.java
> +@AllArgsConstructor
Так data включает getter и setter

2022-09-03 23:36 UTC, tilacyn commented on src/main/java/com/stayaway/request/PlayRequest.java
> +    private CardType cardType;
final нельзя, jacksom не дает

2022-09-03 23:59 UTC, tilacyn commented on src/main/java/com/stayaway/request/PlayRequest.java
> +    private CardType cardType;
сделал

2022-09-04 00:05 UTC, Kowalski1337 requested changes

2022-09-04 00:05 UTC, Kowalski1337 commented on src/main/java/com/stayaway/core/state/ChoosingCardBoardState.java
> +        int handSize = currentPlayer.getCards().size();
В базе может быть что угодно написано. Важно, что ожидается, что сейчас будет выбран номер от 1 до 5. Так что я бы тут с чиселкой 5 сравнивал.

2022-09-04 00:05 UTC, Kowalski1337 commented on src/main/java/com/stayaway/core/state/ChoosingCardBoardState.java
> +            throw ExceptionUtils.notEnoughCardsInHand(cardNumber, handSize);
И название ошибки соответственно не отражает произошедшего. Тут не карт недостаточно, выбран невалидный номер карты

2022-09-04 00:05 UTC, Kowalski1337 commented on src/main/java/com/stayaway/request/PlayRequest.java
> +@AllArgsConstructor
зачем что-то кроме DATA?

2022-09-04 00:06 UTC, Kowalski1337 commented on src/main/java/com/stayaway/request/PlayRequest.java
> +    private CardType cardType;
Да быть не может, сейчас попробую

2022-09-04 00:20 UTC, Kowalski1337 requested changes

2022-09-04 00:20 UTC, Kowalski1337 commented on src/main/java/com/stayaway/controller/GameplayController.java
> +        gameplayManager.discard(new DiscardAction(principal.getName(), request.getCardNumber()), gameId);
request.getCardNumber() - 1 (возможно не здесь, а в стейте)

2022-09-04 00:30 UTC, tilacyn commented on src/main/java/com/stayaway/core/state/ChoosingCardBoardState.java
> +        int handSize = currentPlayer.getCards().size();
Хз не уверен

2022-09-04 00:31 UTC, tilacyn commented on src/main/java/com/stayaway/controller/GameplayController.java
> +        gameplayManager.discard(new DiscardAction(principal.getName(), request.getCardNumber()), gameId);
почему с 1 то а не с нуля

2022-09-04 00:39 UTC, tilacyn commented on src/main/java/com/stayaway/core/state/ChoosingCardBoardState.java
> +            throw ExceptionUtils.notEnoughCardsInHand(cardNumber, handSize);
поправил

2022-09-04 11:38 UTC, merged