STAYAWAYBACK-6 exception handler, board to board response builder
tilacyn/stay-away pull request #5
Opened 2022-08-07 21:03 UTC by Kowalski1337

2022-08-08 20:10 UTC, tilacyn requested changes

2022-08-08 20:10 UTC, tilacyn commented on src/main/java/com/stayaway/dao/model/Move.java
> +    PLAYING_CARD, //todo extend with card
Есть такие ходы как Соблазн, где нужно хранить доп информацию кроме PLAYING_CARD и типа карты. (например, в случае соблазна - какой картой ты меняешься с target)
Замечание на будущее

2022-08-08 20:10 UTC, tilacyn commented on src/main/java/com/stayaway/controller/BoardController.java
> +        List<User> boardPlayers = userService.getBoardPlayers(board);
Наверное можно не использовать здесь userService, если хранить в Player не userID, а userLogin

2022-08-08 20:10 UTC, tilacyn commented on src/main/java/com/stayaway/dao/model/Board.java
> +        private final String userId;
Здесь login предлагаю

2022-08-08 20:10 UTC, tilacyn commented on src/main/java/com/stayaway/controller/BoardController.java
> +@RestController
Надо убрать, потому что не все методы тут rest, метод getBoardPage не будет работать с этой аннотацией.
RestController помимо того, что это просто контроллер означает, что все методы аннотированы еще ResponseBody, что влечет сериализацию объекта возвращаемого в json

2022-08-08 20:10 UTC, tilacyn commented on src/main/java/com/stayaway/proto/builder/BoardResponseBuilder.java
> +public class BoardResponseBuilder {
Мне больше нравится BoardResponseFactory, потому что это по смысле паттерн Factory, а не Builder

2022-08-08 20:10 UTC, tilacyn commented on src/main/java/com/stayaway/dao/model/Board.java
> +    private final List<Player> players;
А как мы будем делать ход - для этого нужно получить player имея userID. Понятно, что player-ов ограниченное количество и поиск по списку работает очень быстро, просто немного глаз режет.
Мб все-таки хранить Map<String, Player> с указателями на следующего и предыдущего?

2022-08-08 20:10 UTC, tilacyn commented on src/main/java/com/stayaway/dao/model/User.java
> +    private final String id;
Вот этот id предлагаю нигде в коде не использовать, завязываться только на login

2022-08-08 20:10 UTC, tilacyn commented on src/main/java/com/stayaway/dao/repository/UserRepository.java
> +    default List<User> usersListByIds(List<String> ids) {
Предлагаю этот метод выпилить

2022-08-08 20:10 UTC, tilacyn commented on src/main/java/com/stayaway/exception/StayAwayException.java
> +public class StayAwayException extends RuntimeException {
Немного напрягает, что предполагается во всех местах приложения понимать, какой httpStatus будет возвращен.
То есть хотелось бы иметь слой ExceptionHandling-а, который маппит Exception на HttpStatus, а не прописывать это статически в коде

2022-08-08 20:24 UTC, tilacyn commented on src/main/java/com/stayaway/exception/StayAwayException.java
> +public class StayAwayException extends RuntimeException {
В любом случае, это если и править, то отдельным пр-ом, думаю

2022-08-08 20:24 UTC, tilacyn commented on src/main/java/com/stayaway/exception/StayAwayExceptionHandler.java
> +    public ResponseEntity<FrontErrorResponse> handleStayAwayException(StayAwayException exception) {
Продолжая мысль в коментарии к StayAwayException, мне кажется, лучше иметь много разных ExceptionHandler методов и мног разных Exception и мапить их здесь на ResponseEntity и http status. То есть сервисы не должны ничего знать про httpStatus

2022-08-08 20:24 UTC, tilacyn commented on src/main/java/com/stayaway/proto/PlayerAction.java
> +public enum PlayerAction {
Эту штуку надо в пакет response

2022-08-08 20:24 UTC, tilacyn commented on src/main/java/com/stayaway/proto/PlayerAction.java
> +public enum PlayerAction {
Весь пакет proto предлагаю перетащить в response

2022-08-10 15:40 UTC, Kowalski1337 commented on src/main/java/com/stayaway/dao/model/Move.java
> +    PLAYING_CARD, //todo extend with card
именно поэтому тут и стоит todo

2022-08-10 15:41 UTC, Kowalski1337 commented on src/main/java/com/stayaway/controller/BoardController.java
> +        List<User> boardPlayers = userService.getBoardPlayers(board);
Оставлю пока так, у нас есть задача на доправить модель, это туда входит

2022-08-10 15:41 UTC, Kowalski1337 commented on src/main/java/com/stayaway/dao/model/Board.java
> +        private final String userId;
Ответил выше

2022-08-10 15:45 UTC, Kowalski1337 commented on src/main/java/com/stayaway/exception/StayAwayException.java
> +public class StayAwayException extends RuntimeException {
Я сделал ровно тоже самое, что ты сказал, только на уровне разных статик методов

2022-08-10 15:47 UTC, Kowalski1337 commented on src/main/java/com/stayaway/exception/StayAwayExceptionHandler.java
> +    public ResponseEntity<FrontErrorResponse> handleStayAwayException(StayAwayException exception) {
Сервисы не знают про статус, но знают про природу ошибки

Не вижу чтоб тут сервис знал про status. А то что сама ошибка умеет себя идентифицировать как ошибка с каким-то http статусом это деталь реализации. И кмк довольно удобно именно так.

throw new NotFounException(message) = throw StartrekException.notFound(message)

2022-08-10 16:06 UTC, merged